export enum Actions {
  KnowledgeBase = 'Knowledge Base',
  AdminPanel = 'Admin Panel',
  Onboarding = 'Onboarding',
  UserManagement = 'User Management',
  KnowledgeBaseManagement = 'Knowledge Base Management',
  OnboardingManagement = 'Onboarding Management',
  LeaveAdminPanel = 'Leave Admin Panel',
  AddUser = 'Add User',
  ViewUsers = 'View Users',
  Back = 'Back',
  Edit = 'Edit',
  Remove = 'Remove',
  AddKnowledgeBaseItem = 'Add Item',
  RemoveKnowledgeBaseCategory = 'Remove Category',
  AddKnowledgeBaseCategory = 'Add Category',
  RemoveKnowledgeBaseItem = 'Remove Item',
}
