export enum Scenes {
  Start = 'start',
  Admin = 'admin',
  User = 'user',
  AddUser = 'add-user',
  EditUser = 'edit-user',
  RemoveUser = 'remove-user',
  KnowledgeBase = 'knowledge-base',
  AddKnowledgeBaseCategory = 'add-knowledge-base-category',
  EditKnowledgeBaseCategory = 'edit-knowledge-base-category',
  RemoveKnowledgeBaseCategory = 'remove-knowledge-base-category',
  AddKnowledgeBaseItem = 'add-knowledge-base-item',
  ViewKnowledgeBaseItems = 'view-knowledge-base-items',
  EditKnowledgeBaseItem = 'edit-knowledge-base-item',
  RemoveKnowledgeBaseItem = 'remove-knowledge-base-item',
  Onboarding = 'onboarding',
}
